# Generated by Django 2.1.7 on 2019-03-04 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20190302_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolvedExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('final_grade', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Solved Exam',
                'verbose_name_plural': 'Solved_exams',
            },
        ),
        migrations.RemoveField(
            model_name='exam',
            name='final_grade',
        ),
        migrations.AddField(
            model_name='solvedexam',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Exam'),
        ),
        migrations.AddField(
            model_name='solvedexam',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='solved_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.SolvedExam'),
        ),
    ]
