# Generated by Django 2.1.7 on 2019-03-06 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_auto_20190306_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_possibility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_answer', to='exams.AnswerPossibility'),
        ),
    ]
