# Generated by Django 2.1.7 on 2019-03-06 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_question_correct_possibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_possibilities',
            field=models.ManyToManyField(blank=True, null=True, to='exams.AnswerPossibility'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_possibility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='default_answer', to='exams.AnswerPossibility'),
        ),
        migrations.AlterField(
            model_name='question',
            name='max_grade',
            field=models.FloatField(default=5, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.QuestionType'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
