# Generated by Django 2.1.7 on 2019-03-14 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_auto_20190306_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reviewer',
            field=models.BooleanField(default=False, verbose_name='user that can change '),
        ),
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.BooleanField(default=True, verbose_name='ordinary user of service'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_possibility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_question', to='exams.AnswerPossibility'),
        ),
    ]
